#! /bin/bash

version=${CHECKOV_VERSION:-'latest'}
if [[ -n ${UPDATE_CHECKOV} ]]; then
  docker pull bridgecrew/checkov:${version}
fi

docker run --rm --tty -v "$(pwd)":/work --workdir /work bridgecrew/checkov:${version} "${@}"
