#! /bin/bash

version=${CHECKOV_VERSION:-'latest'}

last_check=/var/tmp/check-checkov-${version}
if [[ ! -f ${last_check} || $(find ${last_check} -type f -mmin +720) ]]; then
  touch ${last_check}
  echo "Updating bridgecrew/checkov image if necessary..." >&2
  docker pull bridgecrew/checkov:${version}
fi

docker run --rm --tty -v "$(pwd)":/work --workdir /work bridgecrew/checkov:${version} "${@}"
