#! /bin/bash

version=${DIVE_VERSION:-'latest'}

last_check=/var/tmp/check-dive-${version}
if [[ ! -f ${last_check} || $(find ${last_check} -type f -mmin +720) ]]; then
  touch ${last_check}
  echo "Updating wagoodman/dive image if necessary..." >&2
  docker pull wagoodman/dive:${version}
fi

docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)":/work --workdir /work wagoodman/dive:${version} "${@}"
