#! /bin/bash

kube_dir="${KUBECONFIG:-${HOME}/.kube}"

version=${EKSCTL_VERSION:-'latest'}

last_check=/var/tmp/check-eksctl-${version}
if [[ ! -f ${last_check} || $(find ${last_check} -type f -mmin +720) ]]; then
  touch ${last_check}
  echo "Updating weaveworks/eksctl image if necessary..." >&2
  docker pull weaveworks/eksctl:${version}
fi

unset profile_opt
if [[ -n ${AWS_PROFILE} ]]; then
  profile_opt="-e AWS_PROFILE=${AWS_PROFILE}"
fi

docker run --rm -v "${HOME}/.aws":/root/.aws -v "${kube_dir}":/root/.kube -v "$(pwd)":/work --workdir /work ${profile_opt} weaveworks/eksctl:${version} "${@}"
