#! /bin/bash

version=${SYFT_VERSION:-'latest'}
if [[ -n ${UPDATE_SYFT} ]]; then
  docker pull anchore/syft:${version}
fi

docker run --rm -v "$(pwd)":/work --workdir /work anchore/syft:${version} "${@}"
