#! /bin/bash

version=${SYFT_VERSION:-'latest'}

last_check=/var/tmp/check-syft-${version}
if [[ ! -f ${last_check} || $(find ${last_check} -type f -mmin +720) ]]; then
  touch ${last_check}
  echo "Updating anchore/syft image if necessary..." >&2
  docker pull anchore/syft:${version}
fi

docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)":/work --workdir /work anchore/syft:${version} "${@}"
