#! /bin/bash

version=${TRIVY_VERSION:-'latest'}

last_check=/var/tmp/check-trivy-${version}
if [[ ! -f ${last_check} || $(find ${last_check} -type f -mmin +720) ]]; then
  touch ${last_check}
  echo "Updating aquasec/trivy image if necessary..." >&2
  docker pull aquasec/trivy:${version}
fi

docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v trivy-repo:/root/.cache/ -v "$(pwd)":/work --workdir /work aquasec/trivy:${version} "${@}"
